### ISSUE TITLE
V3 BuildOrder - Add fee on both sides of trade

### ISSUE THREAD

**Issue by jinsley8** [trader-xyz/nft-swap-sdk#93]
Can an additional fee be added to both sides of the trade and sent to a 3rd recipient in V3 swap?

I swear I saw settings for it somewhere last week.

Also, what about order expiry time in V3. Is it possible to add?

**Comment by jinsley8** [comment]
Alright, I tested and the options do work but I'm unclear what the following parameters mean:

```
makerFeeAssetData: 0x
takerFeeAssetData: 0x
senderAddress: 0x0000000000000000000000000000000000000000
```

Also, on Polygon can I change makerFee and takerFee to WETH instead of MATIC?

**Comment by wizardlabsxyz** [comment]
Did you figure this out? Curious what you did.

**Comment by jinsley8** [comment]
```
import { defaultAbiCoder } from '@ethersproject/abi';
import { hexConcat } from '@ethersproject/bytes';

/**
 * @param tokenAddress - The ERC20 token address
 * @return The tokenAddress encoded as a bytes
 */
// https://github.com/0xProject/0x-protocol-specification/blob/master/asset-proxy/erc20-proxy.md
export function encodeErc20AssetData(tokenAddress: string): string {
    return hexConcat(['0xf47261b0', defaultAbiCoder.encode(['address'], [tokenAddress])]);
}

const encodeWETHDataMaker = encodeErc20AssetData(
        chain?.id === 137
            ? (process.env.NEXT_PUBLIC_WETH_ADDRESS as string)
            : (process.env.NEXT_PUBLIC_ETH_ADDRESS as string)
);

const encodeWETHDataTaker = encodeErc20AssetData(
        chain?.id === 137
            ? (process.env.NEXT_PUBLIC_WETH_ADDRESS as string)
            : (process.env.NEXT_PUBLIC_ETH_ADDRESS as string)
);
```

```
// used this in BuildOrder
makerFeeAssetData: makerNfts.length > 0 ? encodeWETHDataMaker : '0x',
takerFeeAssetData: encodeWETHDataTaker,
 ```

**Comment by wizardlabsxyz** [comment]
I would prefer if the fee was paid in native token though? I saw in the discord you had mentioned that simply not setting the feeAssetData should work for native token but im getting an error when I do that on mumbai. 


Order Data: Note that the taker fee is in wei (.1 matic)
```
{
  "expirationTimeSeconds": "2524604400",
  "feeRecipientAddress": "0x7890E24087e658978a4eC658a64890961CD98EF9",
  "makerAddress": "0xF4eD4499Eb725B713bEaA84B9c11c0D3B1834ebD",
  "makerAssetAmount": "1",
  "makerAssetData": "0xa7cb5fb70000000000000000000000002953399124f0cbb46d2cbacd8a89cf0599974963000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001a1348c012fee81df544d0ee33d670d47813bf228000000000000010000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000",
  "makerFee": "0",
  "makerFeeAssetData": "0x",
  "salt": "1682575019",
  "senderAddress": "0x0000000000000000000000000000000000000000",
  "signature": "0x1c611af34805060d40ed45e7723e819592d01c36a1ebcb191da23fbb4639650034439b659175cdfe9b0378d7707132b56ccd547388be21ac35d16970d8f943324c02",
  "takerAddress": "0x0000000000000000000000000000000000000000",
  "takerAssetAmount": "1",
  "takerAssetData": "0x0257179200000000000000000000000042cd9ba06cf66cb5faedf66b98a330a68fda09870000000000000000000000000000000000000000000000000000000000000001",
  "takerFee": "100000000000000000",
  "takerFeeAssetData": "0x"
}
```

Error:
```
caught (in promise) Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x0445e028645a40697B5856954681BCD1aC0461FA","to":"0x9866C45224667061F8C9E66Db38D9316A8d68951","data":"0x9b44d556000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000440000000000000000000000000f4ed4499eb725b713beaa84b9c11c0d3b1834ebd00000000000000000000000000000000000000000000000000000000000000000000000000000000000000007890e24087e658978a4ec658a64890961cd98ef90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016345785d8a000000000000000000000000000000000000000000000000000000000000967a67f000000000000000000000000000000000000000000000000000000000644a0eab00000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000003c00000000000000000000000000000000000000000000000000000000000000124a7cb5fb70000000000000000000000002953399124f0cbb46d2cbacd8a89cf0599974963000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001a1348c012fee81df544d0ee33d670d47813bf2280000000000000100000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000440257179200000000000000000000000042cd9ba06cf66cb5faedf66b98a330a68fda09870000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000421c611af34805060d40ed45e7723e819592d01c36a1ebcb191da23fbb4639650034439b659175cdfe9b0378d7707132b56ccd547388be21ac35d16970d8f943324c02000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0x488219a600000000000000000000000000000000000000000000000000000000000000001cca45e29647859a1cf7aebf5c8e40a82ab325d204d4162dec9aa2946c5165d900000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted\",\n    \"data\": \"0x488219a600000000000000000000000000000000000000000000000000000000000000001cca45e29647859a1cf7aebf5c8e40a82ab325d204d4162dec9aa2946c5165d900000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:14454)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:17394)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:18004)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:129727)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:130726\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:64901\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:14454)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:17394)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:21:18004)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:129727)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:130726\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:64901"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at checkError (json-rpc-provider.js:76:1)
    at Web3Provider.eval (json-rpc-provider.js:575:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.js:6:42)
```

**Comment by jinsley8** [comment]
Try this for the address variable for `encodeErc20AssetData`

ETH = `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`
MATIC = `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` or `0x0000000000000000000000000000000000001010`

**Comment by wizardlabsxyz** [comment]
Does this only work on V4? Im using v3 currently.

**Comment by jinsley8** [comment]
Ya sorry, I think only ERC20 are supported on V3.

https://github.com/0xProject/0x-protocol-specification/blob/master/asset-proxy/erc20-proxy.md

**Comment by wizardlabsxyz** [comment]
good to know thanks
